Overhaul of install
This install script for shellfuncs now mimics that of the install
script for my dotfiles.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -4,17 +4,69 @@
 # shell session.
 # Usage: curl --silent https://raw.githubusercontent.com/reap2sow1/shellfuncs/main/install | bash
 set -e
-# shellcheck disable=SC1091
-source "./.env"
-
+PWD="$(pwd)"
+PROGRAM_NAME="install"
+ENV_FILE_NAME=".env"
+TEMP_DIR_NAME="${PROGRAM_NAME}-temp"
+ENV_REMOTE_URL='https://raw.githubusercontent.com/reap2sow1/shellfuncs/main/.env'
 # where this repo is located remotely (doesn't have to be github per say)
 REMOTE_REPO_URL='https://github.com/reap2sow1/shellfuncs'
+
+if [ "$PWD" != "$HOME" ]; then
+    # main reason is to avoid filemode permissions issues
+    echo "${PROGRAM_NAME}: re-run this script in $HOME (assuming you haven't changed this!), to run this correctly"
+    exit 1
+fi
+
+if [ -z "$(which curl)" ]; then
+    echo "${PROGRAM_NAME}: curl cannot be found on the PATH!"
+    exit 1
+fi
+
+if [ -z "$(which git)" ]; then
+    echo "${PROGRAM_NAME}: git cannot be found on the PATH!"
+    exit 1
+fi
+
+mkdir "$TEMP_DIR_NAME" || exit 1
+cd "$TEMP_DIR_NAME" || exit 1
+
+# --fail just means to 'fail' silently without a http status code
+if ! curl --silent --fail "$ENV_REMOTE_URL" -o "$ENV_FILE_NAME"; then
+    echo "${PROGRAM_NAME}: could not fetch $ENV_FILE_NAME from url!"
+    exit 1
+fi
+
+# shellcheck disable=SC1090
+source "./${ENV_FILE_NAME}"
+rm "./${ENV_FILE_NAME}"
+cd ..
+rmdir "$TEMP_DIR_NAME"
 
 if ! [[ "$GIT_REPOS_PATH" ]]; then
     read -r -e -p "What directory are git repositories stored in? ==> " -i "$HOME" GIT_REPOS_PATH <&1
 fi
 LOCAL_REPO_PATH="${GIT_REPOS_PATH}/${LOCAL_REPO_NAME}"
 SCRIPTS_PATH="${LOCAL_REPO_PATH}/${SCRIPTS_DIR_NAME}"
+
+# shellcheck disable=2034
+read -r -e -p "Is this a reinstall, y/n? (n) " RE_INSTALL_REPLY <&1
+
+# using parameter expansion, ',,' append will convert the string to lowercase
+if [ "${RE_INSTALL_REPLY,,}" == "y" ]; then
+    if [ -d "$LOCAL_REPO_PATH" ]; then
+        echo "${PROGRAM_NAME}: the $LOCAL_REPO_NAME still exists on the local file system"
+        echo "$ERROR $DOTFILES_REPO_NAME is the 'dotfiles' repo, and it must be reinstalled first!"
+        read -r -e -p "Has the 'dotfiles' repo been reinstalled, y/n? (n) " DOTFILES_REINSTALLED_REPLY <&1
+        if [ "${DOTFILES_REINSTALLED_REPLY,,}" == "y" ]; then
+            rm -rf "$LOCAL_REPO_PATH"
+        else {
+            echo "${PROGRAM_NAME}: Reinstall the 'dotfiles' repo and then rerun the script"
+            exit 1
+        }
+        fi
+    fi
+fi
 
 git clone --quiet "$REMOTE_REPO_URL" "$LOCAL_REPO_PATH" > /dev/null
 {
