Update test driver
Added usage string and functions headers.
Now the driver can run a single test script at a time.

diff --git a/tests/testshellfuncs_driver b/tests/testshellfuncs_driver
--- a/tests/testshellfuncs_driver
+++ b/tests/testshellfuncs_driver
@@ -2,9 +2,47 @@
 #
 # shellcheck disable=1090
 
-# TODO(conner@conneracrosby.tech): add usage str
+#######################################
+# Usage string for the program.
+# Globals:
+#   PROGRAM_NAME
+# Outputs:
+#   - usage heredoc string to stdout
+# Returns:
+#   0 - cat success
+#   1 - cat error
+#######################################
+usage () {
+	cat << _EOF_
+Usage: $PROGRAM_NAME [-h] [-t TESTSHELLFUNCS_FILENAME]
 
-# TODO(conner@conneracrosby.tech): add function header
+Options:
+	-t	specify a single test program/script to run
+
+_EOF_
+	return
+}
+
+#######################################
+# Used to run testshellfuncs programs. 
+# Allows in defined cases to rerun program(s) 
+# if the re-running requires subtle changes.
+# Globals:
+#   SUDO_PASSWORD
+#   SKIPPING_TEST_MESSAGE
+#   SHELLFUNCS_TEST_SCRIPTS_ENV_PATH
+#	MUST_BE_ROOT_STATUS_CODE
+#	TRYING_TEST_AGAIN_MESSAGE
+# Arguments:
+#   $1: program/script name
+#   $2: previous status code of the program/script ($1)
+# Outputs:
+#   - Success/error messages to stdout
+# Returns:
+#   0 - general success
+#   1 - general error
+#	MUST_BE_ROOT_STATUS_CODE
+#######################################d
 run_testshellfunc_program() {
 	FILENAME="$1"
 	PREVIOUS_STATUS_CODE="$2"
@@ -44,10 +82,32 @@ run_testshellfunc_program() {
 # (or at least be ok with run_testshellfunc_program returning non-zero status codes) 
 . "$SHELLFUNCS_TEST_SCRIPTS_ENV_PATH"
 
-for f in ./*
+# NOTE: name is unset incase it has been defined previously;
+# getops will place the next option (e.g. o, t) into name;
+unset name
+while getopts "ht:" opt; do
+	case "$opt" in
+	"t")    TESTSHELLFUNCS_PROGRAMS=$OPTARG
+			;;
+	"h")	usage
+			exit 0
+			;;
+	":")    echo "${PROGRAM_NAME}: an argument is required for -- $OPTARG"
+			exit 1
+			;;
+    *)		;;
+    esac
+done
+
+# for now the default will be to run all test programs
+# NOTE: globbing pattern should be generalized with exceptions
+# being handled in the below case statement
+if [ -z "$TESTSHELLFUNCS_PROGRAMS" ]; then
+	TESTSHELLFUNCS_PROGRAMS="*"
+fi
+
+for f in $TESTSHELLFUNCS_PROGRAMS
 do
-	# removing the $PWD notation './' from the file name
-	f="${f:2:${#f}}"
     case "$f" in
 		"$(basename "$SHELLFUNCS_TEST_SCRIPTS_ENV_PATH")")		;;
 		"common_tests")											;;
