Refactor script headers, add exit codes to funcs

diff --git a/scripts/shellfuncs_install_codium_extension b/scripts/shellfuncs_install_codium_extension
--- a/scripts/shellfuncs_install_codium_extension
+++ b/scripts/shellfuncs_install_codium_extension
@@ -14,6 +14,9 @@
 #   $2: codium extension version 
 # Outputs:
 #   - Success/error messages to stdout
+# Returns:
+#   0 - general success
+#   1 - general error
 #######################################
 shellfuncs_install_codium_extension () {
     EXTENSION="$1"
@@ -22,7 +25,7 @@ shellfuncs_install_codium_extension () {
         echo -e "$ERROR extension is required as \$1"
         return 1
     elif [ -z "$EXTENSION_VERSION" ]; then
-        echo -e "$ERROR extension <version> is required as \$2"
+        echo -e "$ERROR extension version is required as \$2"
         return 1
     fi
     # mhutchie.git-graph is an example of a codium extension
@@ -32,7 +35,7 @@ shellfuncs_install_codium_extension () {
     OUTPUT_FILE_NAME="$EXTENSION_PUBLISHER.$EXTENSION_NAME-$EXTENSION_VERSION.vsix"
     EXT_URL="https://marketplace.visualstudio.com/_apis/public/gallery/publishers/$EXTENSION_PUBLISHER/vsextensions/$EXTENSION_NAME/$EXTENSION_VERSION/vspackage"
     if ! wget --quiet --output-document="$OUTPUT_FILE_NAME_GZ" "$EXT_URL"; then
-        echo -e "$ERROR failed to <download> $EXTENSION!"
+        echo -e "$ERROR failed to download $EXTENSION!"
         return 1
     fi
     # wget downloads files compressed as gzip
@@ -41,7 +44,7 @@ shellfuncs_install_codium_extension () {
     # NOTE: installing a new extension will overwrite any previous version installed
     # NOTE2: weirdly installing an extension successfully may still signal an issue...
     # might have todo with exceptions thrown from installation (even though the installation works)
-    codium --install-extension "$OUTPUT_FILE_NAME"
+    codium --install-extension "$OUTPUT_FILE_NAME" || return 1
     rm "$OUTPUT_FILE_NAME_GZ"
     rm "$OUTPUT_FILE_NAME"
     echo -e "$SUCCESS installed $EXTENSION $EXTENSION_VERSION successfully"
